### ISSUE TITLE
DBのテーブル構成を考える

### ISSUE THREAD

**Issue by pyama86** [honeymoon-answer/answer#1]
# 必要そうなテーブル
## ユーザー情報・認証情報テーブル
  - Slack認証するからoauth token持つ必要がある
  - ユーザー情報と一緒で良いかなと思う

## アンケート(仮)テーブル
 - アンケートの本文を持つ
   - 本文
   - リマインド間隔
   - アンケート属性(複数押せる、押せない、押したらトグルみたいにon、offになるとか)

## アンケート送った人テーブル
  - リマインドするのに送った他人事にレコードが必要かな
    - may be ユーザー情報とアンケートテーブルの中間テーブルで良さそう

## アンケート選択肢テーブル
 - アンケートで押されるボタンの情報を持つ
   - name/id

## アンケートボタン押された結果テーブル
 - データを蓄積しまくるテーブル

ざっくりこんな感じ？

**Comment by hypermkt** [comment]
> ユーザー情報と一緒で良いかなと思う

Slack前提で実装するので、自分もそれで良いかと思いました 👍 

> アンケート属性(複数押せる、押せない

選択肢に対して、選択できるのは必ず一つだと思ってましたが複数の場合もあるということですかね〜。ちなみにどんなケースでしょう？？

> 押したらトグルみたいにon、offになるとか

こちらも利用するイメージが付きませんでした。質問と選択肢の例があれば、教えてもらえると助かります！

> アンケート選択肢テーブル

https://github.com/honeymoon-answer/answer/issues/5#issuecomment-317900363 の要件では、完了ボタン固定で考えていましたが、そういえばMTG時にアンケート作成時に選択肢は複数個追加できるという話をしていましたね。

> アンケートボタン押された結果テーブル

アンケート送った人テーブルに結果カラムを持たせれば、人別に結果を保持できるので、このテーブルは不要かと思いましたがどうでしょう？

**Comment by takumakume** [comment]
> 選択肢に対して、選択できるのは必ず一つだと思ってましたが複数の場合もあるということですかね〜。ちなみにどんなケースでしょう？？

わたしは、飲み会の候補日みたいな用途で
- 7/21
- 7/22
- 7/23

全部行ける人は全部押すことができる。みたいな用途も思っていました！

**Comment by hypermkt** [comment]
> 飲み会の候補日みたいな用途, 全部行ける人は全部押すことができる

なるほど！そういった用途もあるでしょうし、出来たほうが良いですね。了解です！

> アンケート送った人テーブルに結果カラムを持たせれば、人別に結果を保持できるので、このテーブルは不要かと思いましたがどうでしょう？

アンケートボタン押された結果テーブル は複数候補日に対応するために必要でした！

**Comment by pyama86** [comment]
>選択肢に対して、選択できるのは必ず一つだと思ってましたが複数の場合もあるということですかね〜。ちなみにどんなケースでしょう？？

これは先の通り飲み会の日程とかですかね。

> 押したらトグルみたいにon、offになるとか
> こちらを利用するイメージが付きませんでした。質問と選択肢の例があれば、教えてもらえると助かります！

押し間違えたときとか、ON、OFF出来たら嬉しくないですか？なんかそんな用途をふわっと考えていた。

**Comment by hypermkt** [comment]
> 押し間違えたときとか、ON、OFF出来たら嬉しくないですか？なんかそんな用途をふわっと考えていた。

確かにボタンの押し間違えはありえるので、ON/OFFできると良さそうですね。

**Comment by pyama86** [comment]
on、off出来るかどうかがふわっとしてるからどっか時間見つけて、手動でapi叩いてボタン作ってみよ。

**Comment by hypermkt** [comment]
Message Button/Menuには、[確認用のポップアップ](https://api.slack.com/docs/interactive-message-field-guide#confirmation_fields)を出す機能があるので、これを使えば押し間違い防止にも繋がりそうですね。

![slack_confirm](https://user-images.githubusercontent.com/1726225/28830764-b43059c2-7712-11e7-8856-0cb0dce46bdd.gif)

**Comment by hypermkt** [comment]
## [WIP] テーブル作成案
Message Buttonsの[Field Guilde](https://api.slack.com/docs/interactive-message-field-guide)と比較しながら検討中・・・。

* 【済】users ユーザー情報・認証情報テーブル
    * access_token
    * user_name
* messages アンケート(仮)テーブル
    * user_id
    * messge:text
    * dut_at:datetime
    * require_confirm:boolean
    * remind_interval:integer
        * 0: 10min, 1: 1hour, 2: 1day, 3: 1week
* mentioned_users アンケート送った人テーブル
    * message_id
    * user_name: メンションされたユーザー名
        * users_idと思ったが、このシステムを利用時点でメンション先ユーザーが全て登録済みとも限らない。またユーザー名文字列でDMは送れるので十分。
* message_buttons アンケート選択肢テーブル
    * message_id
    * name: ユーザーがWeb画面から入力したボタン名の文字列
    * value: システムが発行したユニーク値。ボタンクリック時にAction URLに付与して送信される。取得した値から何を選択したか判定するために利用する。
* answers アンケートボタン押された結果テーブル
    * message_id
    * mentioned_user_id
    * message_button_id

**Comment by pyama86** [comment]
> users_idと思ったが、このシステムを利用時点でメンション先ユーザーが全て登録済みとも限らない。またユーザー名文字列でDMは送れるので十分。

SlackのユーザーIDでいいんじゃないかな。

**Comment by hypermkt** [comment]
Slack上でコメント済みですが、[多分SlackのユーザーID(例: U023BECGF)でもDMが送信できる](https://api.slack.com/methods/chat.postMessage)と思うのでそうしましょう。あとで検証してみます。

カラム名ですが、usersテーブルのidカラムと意味合いを分けるため、slack_user_idでどうでしょう？

**Comment by hypermkt** [comment]
アプリケーション名と同じ名前は使えなかったー。

```sh
$ be rails g model Answer message:references mentioned_user:references message_button:references
Running via Spring preloader in process 32657
      invoke  active_record
The name 'Answer' is either already used in your application or reserved by Ruby on Rails. Please choose an alternative and run this generator again.
```

**Comment by hypermkt** [comment]
message_answersテーブルにした。「アンケートボタン押された結果テーブル」との事からresultも考えたが、

* answerは、質問の回答、電話・手紙への応答
* resultは、出来事の結果、調査による発見

という意味合いを考慮すると今回の用途では`answer`が適切。とはいえ、アプリケーション名との重複からmessage_answersに妥協した。

* [answer Meaning in the Cambridge English Dictionary](http://dictionary.cambridge.org/dictionary/english/answer)
* [result Meaning in the Cambridge English Dictionary](http://dictionary.cambridge.org/dictionary/english/result)

**Comment by hypermkt** [comment]
## TODO
- [ ] messages.remind_intervalカラムは不要になったので削除する

**Comment by hypermkt** [comment]
モデル・マイグレーションに落とし込めたのでクローズします。後は作りながら調整していきましょう。
