### ISSUE TITLE
Sign in with Slack機能について調べる

### ISSUE THREAD

**Issue by hypermkt** [honeymoon-answer/answer#13]
実現方法と取得できる情報について知りたい〜。

### 関連
* [DBのテーブル構成を考える · Issue \#1 · honeymoon\-answer/answer](https://github.com/honeymoon-answer/answer/issues/1)
    * 格納する情報の判断に、本件の理解が必要。

### 参考
* [Sign in with Slack \| Slack](https://api.slack.com/docs/sign-in-with-slack)
* [PHPでSignin with Slackを試す \- Qiita](http://qiita.com/suzutan/items/4070613f356ce0311ce3)
* [Slack認証 \+ Rails によるログイン画面を一から作る方法 \- Qiita](http://qiita.com/toririn/items/b0031894375616077fc4)

**Comment by hypermkt** [comment]
https://github.com/honeymoon-answer/answer/pull/34 で完了

**Comment by pyama86** [comment]
issueあったんだ。
