### ISSUE TITLE
API設計

### ISSUE THREAD

**Issue by takumakume** [honeymoon-answer/answer#21]
AnswerのバックエンドのRestfulAPIの設計をします。
以下のように必要なAPIを定義する。

----

## List messages

List the authenticated user's messages

```
GET /messages
```

#### Parameters

Name | Type | Description
---      | ---    | ----
 | | 

#### Response

- Status: 200 OK

```json
{

}
```

----

## Create message

```
POST /messages
```

#### Inputs

Name | Type | Description
---      | ---    | ----
user_id | int | メッセージ作成者
message | string | メッセージ本文
require_confirm | bool | 確認メッセージを表示するか

#### Response

- Status: 201 Created

```json
No Contents
```

**Comment by hypermkt** [comment]
API設計は全て完了したのでクローズします。
