### ISSUE TITLE
あれ・・・スキーマなんか・・・あれじゃない？

### ISSUE THREAD

**Issue by pyama86** [honeymoon-answer/answer#26]
気づかなかったのだけど、

https://github.com/honeymoon-answer/answer/blob/master/db/schema.rb#L44

ここって、slack_usersのidが入るべきじゃないかなとか、usersはslack_usersじゃなくて、usersで良さそう。
その中に、idとslack_idがあると良いのではないかなと思ったけど、どうだろう。

**Comment by hypermkt** [comment]
> slack_usersのidが入るべきじゃないかな

messages.slack_user_idカラムにslack_users.idが入るのか？ということですね。これは入る想定です。

> CONSTRAINT `fk_rails_badf58c47e` FOREIGN KEY (`slack_user_id`) REFERENCES `slack_users` (`id`)

slack_users.idを利用する外部キー制約を設定しています。

```sql
CREATE TABLE `messages` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `slack_user_id` bigint(20) DEFAULT NULL,
  `message` text COMMENT 'Request message',
  `dut_at` datetime DEFAULT NULL COMMENT 'Due to answer the request',
  `require_confirm` tinyint(1) DEFAULT '0' COMMENT 'Flag to use confirmation dialog',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `index_messages_on_slack_user_id` (`slack_user_id`),
  CONSTRAINT `fk_rails_badf58c47e` FOREIGN KEY (`slack_user_id`) REFERENCES `slack_users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

**Comment by hypermkt** [comment]
> usersはslack_usersじゃなくて、usersで良さそう。
> その中に、idとslack_idがあると良いのではないかなと思ったけど、どうだろう。

すいません、これは自分の共有漏れでした。先日チャットで合意をとったので、返事には相談すべきでした。

* https://github.com/honeymoon-answer/answer/pull/18/commits/326f5855f2176b8a26d52c5144bfb3bb63cf84cc

**Comment by hypermkt** [comment]
> usersはslack_usersじゃなくて、usersで良さそう。
> その中に、idとslack_idがあると良いのではないかなと思ったけど、どうだろう。

すいません、これは自分の相談＆共有漏れでした :bow: 先日チャットで合意をとったので、事前に相談すべきでした。

以下にて、テーブル名とカラム名の変更をしました。

* https://github.com/honeymoon-answer/answer/pull/18/commits/326f5855f2176b8a26d52c5144bfb3bb63cf84cc
* https://github.com/honeymoon-answer/answer/pull/18/commits/dd46c2514db1a1267c0b8d802c489ad4bef054dd

テーブル名を変更した理由は「Slack前提」という説明がなくても、コードからSlackユーザーを格納しているという事が伝わると分かりやすいと思い、モデルにSlackを付けたく、slack_usersテーブルにしました。

カラム名をslack_idからuser_idにしたのは、値として入るのはSlackのユーザーIDなので、user_idの方が正しいのではと思いそうしました。ですが、「menstions.user_id」を見ると、SlackのユーザーIDかどうかはカラム名からは分からないので、当初通り「slack_id」の方が良いと思いました。

1. テーブル名 slack_users -> usersに戻す
2. カラム名 slack_users.user_id -> slack_users.slack_id と mentions.user_id -> mentions.slack_idに戻す

改めて再考して2番は戻すべきだと思いました。1番についても戻したほうが良いか意見もらえると助かります。

**Comment by pyama86** [comment]
> カラム名 slack_users.user_id -> slack_users.slack_id と mentions.user_id -> mentions.slack_idに戻す

mentions.user_idで良いのじゃないかなぁ。コードとしては常にプライマリキーをインターフェースに持っていくべきで、Slackと喋らなきゃけいないときに、users.slack_idを都度呼び出すという規約のほうがしんぷるでよいかなぁと思いました。

**Comment by pyama86** [comment]
ああ、ちゃうな、メンション先が既にuser登録されているかわからんからそうなのか。

**Comment by hypermkt** [comment]
> ああ、ちゃうな、メンション先が既にuser登録されているかわからんからそうなのか。

そうなんです、メンション先のSlackユーザーは、本システムにユーザー登録されていないユーザーがほとんどだと思います。

なので、mentions.user_idは、（現）slack_users.user_idの参照ではなく、アンケート作成画面で指定され送信されてきたSlackのユーザーIDを格納する想定で考えていました。
