### ISSUE TITLE
メッセージの送信の仕組みを考える

### ISSUE THREAD

**Issue by takumakume** [honeymoon-answer/answer#31]
依頼作成ボタンを押した後に、SlackのDMを使って依頼メッセージを送信する仕様になる。
その際に大量に宛先があった時に課題がありそうなので、どう送るかを決める。

- Slack APIのRatelimitに掛かることはないか
- 依頼作成ボタンを押した後に待ち時間が発生しそう

Slack APIドキュメントのrate-limitsの章を見る限り
https://api.slack.com/docs/rate-limits

> ### Message Posting
> In general we allow applications that integrate with Slack to send no more than one message per second. We allow bursts over that limit for short periods. However, if your app continues to exceed the limit over a longer period of time it will be rate limited.

- 通常アプリでは1秒に1回しかメッセージが送れない
- 短期間のバースト的なAPIの利用は許可されるが、長期に渡って大量利用すると制限される

感じだった。

メッセージの送信に関してもSidekiqなどを使ってJobにしたほうが良さそうだ。

**Comment by tnmt** [comment]
#43 #50 でやります
