### ISSUE TITLE
残作業を整理する

### ISSUE THREAD

**Issue by takumakume** [honeymoon-answer/answer#35]
## 必要な作業

`【当日】` は当日作業でも良さそうなもの

### API周り

- [x] APIベース
- [ ] messages (assigned: )
- [ ] message_buttons (assigned: )
- [ ] message_answers (assigned: )
- [ ] mentions (assigned: )
- [ ] sessions (assigned: )

### UI周り

- [x] モックアップ
  - [x] users#sign
  - [x] messages#index
  - [x] messages#create
- [ ] プロトタイプからAPIを用いた実装へ
  - [ ] users#sign (assigned: )
  - [ ] messages#index (assigned: )
  - [ ] messages#create (assigned: )
- [ ] UIデザインの最適化 (assigned: )
- [ ] 【当日】messages#createのメンション箇所のインクリメンタルサーチ化 (assigned: )

### リマインド周り

- [ ] RemindJobの実装

### Heroku周り

- [ ] 【当日】アイコン作成 (assigned: )

### その他

- [ ] 【当日】Slack APIのget系の処理のキャッシュ化 (assigned: )
- [ ] 【当日】アプリ名の決定と環境への適応 (assigned: )
- [ ] 【当日】社のSlackで利用可能な状態にする (assigned: )

**Comment by takumakume** [comment]
UI実装の兼ね合いがあるので、最優先はAPIの実装かな

**Comment by pyama86** [comment]
なんと・・・Githubにはプロジェクトと言う機能があってですね・・・

**Comment by takumakume** [comment]
なるほど。。
