### ISSUE TITLE
Message Buttonのクリックした情報を受け取るエントリポイントの設計

### ISSUE THREAD

**Issue by hypermkt** [honeymoon-answer/answer#49]
### 参考
* [Responding to message actions](https://api.slack.com/docs/message-buttons)

**Comment by hypermkt** [comment]
コールバック先のURLはここで指定する。

![image](https://user-images.githubusercontent.com/1726225/29612823-25c7c75a-883e-11e7-9256-cef41540f24c.png)

**Comment by hypermkt** [comment]
@honeymoon-answer/all 

Message Buttonをクリック時にSlackからリクエストされ、それを受け取るエントリポイントですが、

`POST /api/v1/slack/interactive-messages/action`

で、どうでしょう？

理由としてはInteractive Messages（Message Button, Menu）のボタンを押す・メニューを選択するなどのアクションがあった際に、リクエストを受け取るエントリポイントであることが明確になります。

### メモ

![image](https://user-images.githubusercontent.com/1726225/29613358-98d615a6-8840-11e7-9bc6-ab1156100085.png)

**Comment by takumakume** [comment]
エントリポイントについて、わたしはいいと思いました！

![image](https://user-images.githubusercontent.com/10905048/29616208-b5282482-884b-11e7-90c2-755cf8c9477f.png)
今回Menuも実装するなら、APIもそこを考慮しないといけないですね

**Comment by pyama86** [comment]
とても良さそう。こういうのだいたいcallbackって入れることが多いと思いますが、そこはよいかな？

**Comment by hypermkt** [comment]
最初は`callback`という文字列を入れていたのですが、何かを受信するというイメージがないという意見があったので外しました。今思い返すとやはりあったほうが良い気がしてきました。

もしcallbackを入れる場合は、以下の２つが考えられますが、Interactive Messageのコールバックとしては、2番でも十分意味が通じそうですがどうでしょうか。

1. `/api/v1/slack/interactive-messages/action/callback`
1. `/api/v1/slack/interactive-messages/callback`

**Comment by pyama86** [comment]
後者かなぁ。なんかでも僕がいったことが全部通る世の中もなかなかポイズンになりつつありますね。

callbackとした方が良いかもなと思っている理由を述べると、何か外部から叩かれるエンドポイントであるとすぐわかるからということです。
そしてそれが一般的なので、OSSにするならそれに習う方が良かろうという気持ち。

**Comment by tnmt** [comment]
並べると後者が良さそうー

**Comment by hypermkt** [comment]
> /api/v1/slack/interactive-messages/callback

にしたいと思います！

当初はcallbackというのは不要と思いましたが、一般的にはcallbackが使われているという観点が抜けてたので必要だと思いました！ポイズンですが、最初から気づけるようにしたいですね。

**Comment by hypermkt** [comment]
決まったので閉じます！
