### ISSUE TITLE
要件をまとめる

### ISSUE THREAD

**Issue by hypermkt** [honeymoon-answer/answer#5]
プレゼン資料を元に要件をまとめる。

**Comment by hypermkt** [comment]
プレゼン資料を元に要件を整理してみました📝 。記憶を辿りながら書いているのでどこか間違ってるかも。自由に加筆修正しちゃってください。 

## 用語
* アンケートメッセージ
    * アンケートの登録が完了した際に、指定チャンネルで投稿されたメッセージ

## 要件

### ユーザー
* Slack認証を利用したユーザー登録ができる
    * 指定されたSlackチームしかユーザー登録は出来ない
* ログインできる

### アンケート
* アンケートの登録ができる
    * 以下項目が登録できる
        * 本文
        * Slackチャンネル
        * メンション先 Slackユーザー又はグループ
        * リマインド間隔 (後で資料を確認する)
    * アンケートを登録すると、指定のSlackチャンネルで本文とメンション先が書かれたメッセージがコメントされる。
* アンケートの編集・削除ができる
* アンケートの一覧が表示できる

### アンケートメッセージ

![image](https://user-images.githubusercontent.com/1726225/28597633-feeb59f0-71d9-11e7-9841-e04ca16b2fc5.png)

* アンケートメッセージには、本文・メンション先・完了ボタンが表示される
    * ボタン名は「完了」ボタン固定である
* メンションを受けたユーザーは、本文のタスクが完了している場合は完了ボタンを押す
    * 【疑問】SlackのMessage Buttonは複数人のに対応しているのかな？
* メンションを受けたユーザーが完了ボタンを押さなかった場合、アンケート登録された日付を基準に指定されたリマインド間隔で、DMにより通知が行く

**Comment by hypermkt** [comment]
## 疑問
- [ ] SlackのMessage Buttonは、複数人が個別に完了ボタンが押せるんだろうか。

**Comment by hypermkt** [comment]
test

**Comment by takumakume** [comment]
test

**Comment by pyama86** [comment]
>  SlackのMessage Buttonは、複数人が個別に完了ボタンが押せるんだろうか

これだめだったらなおさら個人宛投稿だけになっちゃうな。

> アンケート投稿者は、どうやってメンション先の全員が完了ボタンを押したことを知るんだろうか

webに見に行く契機ってことですかねぇ。正ならば能動的に見に行くで良さそうだけど何かグッドソリューションあったら聞きたいです！

> アンケート投稿者は、どうやって完了ボタンが押されたかの進捗を知るんだろうか

WebUIがあります！

**Comment by hypermkt** [comment]
> これだめだったらなおさら個人宛投稿だけになっちゃうな。

これは検証してみますね。別案としては、アンケート本文の下に ✅  の絵文字を表示させて、そのクリック状態で判定するとか。

> webに見に行く契機ってことですかねぇ。正ならば能動的に見に行くで良さそうだけど何かグッドソリューションあったら聞きたいです！

こちらも下記同様にアンケート詳細画面があれば、確認できますね。別案としては

* リマインド時に、アンケート登録者にも別途DMで進捗情報を共有する
* ボットを用意してそこに進捗状況を問い合わせる

とかですかね〜。

> WebUIがあります！

そうですね！ アンケート詳細画面を用意して、そこで閲覧できるようにしましょう。

**Comment by hypermkt** [comment]
pyamaさんが提示してくれた[テーブルの構成案](https://github.com/honeymoon-answer/answer/issues/1#issue-245471783)で、アンケートに対する選択肢は複数個設定できるのを思い出したので https://github.com/honeymoon-answer/answer/issues/5#issuecomment-317900363 に反映しました。 もし間違ってたら教えてください！修正してもらっても構いません！

**Comment by hypermkt** [comment]
## [WIP] SlackのMessage Buttonは、複数人が個別に完了ボタンが押せるか検証中
[検証用のスクリプト](https://github.com/hypermkt/slack-message-buttons/blob/master/index.js)を用意して、以下Message Buttonを表示させてみた。

![image](https://user-images.githubusercontent.com/1726225/28682401-c09e95c2-7337-11e7-8fb8-78a284d0959f.png)

完了ボタンを押した際にメッセージを別のものに書き換えた場合、他のユーザーが見るとどうなるのか？（予想は全員変更されたメッセージになる）

* Slack App内で
    * bot userを有効にした
    * `chat:write:bot`のスコープを許可した
        * ![image](https://user-images.githubusercontent.com/1726225/28682626-91ba7db0-7338-11e7-9674-27dcb0c177d6.png)
    * heroku側に `Bot User OAuth Access Token`を環境変数で持たせた

上記の状態で完了ボタンを押すと ``body: {"ok":false,"error":"cant_update_message"}``をログ出漁されて失敗する。ドキュメントによると、 `Authenticated user does not have permission to update this message.` とのことで権限がないとのこと。うーむ、許可したつもりなのだが、どこを間違えているんだろう。

**Comment by hypermkt** [comment]
このIssueとは別の課題ったので、Issueを分けました https://github.com/honeymoon-answer/answer/issues/11

**Comment by hypermkt** [comment]
難しく考えずコードファーストで行こう。
